conky.config = {
  update_interval      = 1,
  background           = false,
  own_window           = true,
  own_window_type      = 'normal',
  own_window_class     = 'Conky',
  own_window_hints     = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  draw_blended         = false,
  own_window_argb_visual = true,
  own_window_transparent = true,
  own_window_argb_value  = 0,
  own_window_colour    = '241F31',

  alignment            = 'bottom_left',
  gap_x                = 70,
  gap_y                = 25,
  minimum_width        = 418,
  maximum_width        = 418,
  minimum_height       = 418,

  double_buffer        = true,
  use_xft              = true,
  xftalpha             = 1.0,

  font                 = 'Inter:size=11',
  default_color        = 'FFFFFF',

  draw_borders         = false,
  draw_shades          = true,
  draw_outline         = false,
  draw_graph_borders   = false,
}

conky.text = [[
${image ~/.config/conky/reverie/res/lg_darker.png -p 0,240 -s 108x108}${image ~/.config/conky/reverie/res/lg_darker.png -p 118,240 -s 108x108}${image ~/.config/conky/reverie/res/lg_darker.png -p 238,240 -s 108x108}${font Inter:bold:size=38}Hello
${voffset -19}${font Inter:bold:size=30}It's ${color 29B6F6}${time %A}.
${color FFFFFF}${font Inter:size=7}
${font Hack Nerd Font:size=19}󰍎 ${font Inter:size=13}${cat /tmp/conky_wcity}
${font Hack Nerd Font:size=19}󰀄 ${font Inter:size=13}${exec echo $USER}${voffset -1}
${font Inter:size=8}
${font Inter:size=0}${execi 60 bash ~/.config/conky/reverie/scripts/weather.sh}${font}
${voffset -1}${goto 41}${font Inter:size=19}${time %H}${goto 160}${font Hack Nerd Font:size=26}${color 29B6F6}${cat /tmp/conky_wicon}${color FFFFFF}${goto 276}${font Inter:bold:size=24}${color 29B6F6}${time %-d}
${voffset -18}${goto 40}${font Inter:size=19}${color 29B6F6}•${color FFFFFF}•${goto 148}${voffset 6}${font Hack:size=18}${color FFFFFF}${cat /tmp/conky_wtemp}°C${color FFFFFF}${goto 274}${voffset -1}${font Inter:bold:size=19}${time %b}
${voffset -9}${goto 41}${font Inter:size=19}${color 29B6F6}${time %M}${color FFFFFF}

${font Inter:size=11}${color FFFFFF}${exec playerctl metadata --format '{{artist}} - {{title}}' 2>/dev/null || echo 'No music played'}${color}
]]
